name: LUcompute
channels:
  - conda-forge
dependencies:
  - gcc # [osx]
  - matplotlib
  - python=3.7
  - bokeh
  - ipywidgets
  - jupyter
  - notebook
  - numpy
  - openpyxl
  - pandas
  - pip
  - scipy
  - seaborn
  - pip
  - xlrd
  - cryptography
  - simplegeneric
  - r-essentials
  - rpy2
  - cython
  - geopandas
